// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pkg/streaming/proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_streaming_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payloads      [][]byte               `protobuf:"bytes,2,rep,name=payloads,proto3" json:"payloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_streaming_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *AddRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AddRequest) GetPayloads() [][]byte {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_pkg_streaming_proto_event_proto_rawDescGZIP(), []int{2}
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	MaxEvents     int32                  `protobuf:"varint,2,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_pkg_streaming_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *PollRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PollRequest) GetMaxEvents() int32 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_streaming_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_pkg_streaming_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *PollResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_pkg_streaming_proto_event_proto protoreflect.FileDescriptor

const file_pkg_streaming_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/streaming/proto/event.proto\x12\tstreaming\"?\n" +
	"\x05Event\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\">\n" +
	"\n" +
	"AddRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bpayloads\x18\x02 \x03(\fR\bpayloads\"\r\n" +
	"\vAddResponse\"B\n" +
	"\vPollRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"max_events\x18\x02 \x01(\x05R\tmaxEvents\"8\n" +
	"\fPollResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.streaming.EventR\x06events2\x7f\n" +
	"\fEventService\x124\n" +
	"\x03Add\x12\x15.streaming.AddRequest\x1a\x16.streaming.AddResponse\x129\n" +
	"\x04Poll\x12\x16.streaming.PollRequest\x1a\x17.streaming.PollResponse0\x01B\x15Z\x13pkg/streaming/protob\x06proto3"

var (
	file_pkg_streaming_proto_event_proto_rawDescOnce sync.Once
	file_pkg_streaming_proto_event_proto_rawDescData []byte
)

func file_pkg_streaming_proto_event_proto_rawDescGZIP() []byte {
	file_pkg_streaming_proto_event_proto_rawDescOnce.Do(func() {
		file_pkg_streaming_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_streaming_proto_event_proto_rawDesc), len(file_pkg_streaming_proto_event_proto_rawDesc)))
	})
	return file_pkg_streaming_proto_event_proto_rawDescData
}

var file_pkg_streaming_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_streaming_proto_event_proto_goTypes = []any{
	(*Event)(nil),        // 0: streaming.Event
	(*AddRequest)(nil),   // 1: streaming.AddRequest
	(*AddResponse)(nil),  // 2: streaming.AddResponse
	(*PollRequest)(nil),  // 3: streaming.PollRequest
	(*PollResponse)(nil), // 4: streaming.PollResponse
}
var file_pkg_streaming_proto_event_proto_depIdxs = []int32{
	0, // 0: streaming.PollResponse.events:type_name -> streaming.Event
	1, // 1: streaming.EventService.Add:input_type -> streaming.AddRequest
	3, // 2: streaming.EventService.Poll:input_type -> streaming.PollRequest
	2, // 3: streaming.EventService.Add:output_type -> streaming.AddResponse
	4, // 4: streaming.EventService.Poll:output_type -> streaming.PollResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_streaming_proto_event_proto_init() }
func file_pkg_streaming_proto_event_proto_init() {
	if File_pkg_streaming_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_streaming_proto_event_proto_rawDesc), len(file_pkg_streaming_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_streaming_proto_event_proto_goTypes,
		DependencyIndexes: file_pkg_streaming_proto_event_proto_depIdxs,
		MessageInfos:      file_pkg_streaming_proto_event_proto_msgTypes,
	}.Build()
	File_pkg_streaming_proto_event_proto = out.File
	file_pkg_streaming_proto_event_proto_goTypes = nil
	file_pkg_streaming_proto_event_proto_depIdxs = nil
}
